name: Build

on: workflow_call

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - run: sudo apt-get install -y ttfautohint zip
      - run: build.sh
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: |
            dist/*
            Lode-*.zip
