name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - run: sudo apt-get install -y ttfautohint
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: Lode-TTC-$(git rev-parse --short HEAD).zip
          path: 'dist/*.ttc'
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: Lode-WOFF2-$(git rev-parse --short HEAD).zip
          path: 'dist/*.woff2'
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
