name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_type: full
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: Lode-*.zip
      - uses: softprops/action-gh-release@v2
        with:
          files: Lode-*.zip
          generate_release_notes: true
