name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - run: sudo apt-get install -y ttfautohint zip
      - run: LODE_BUILD=full ./build.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: '*.zip'
          generate_release_notes: true
