name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: Lode-*.zip
          generate_release_notes: true
