name: Release
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - run: sudo apt-get install -y ttfautohint zip
      - run: ./build.sh
      - run: zip -j -X -9 "Lode-${{ github.ref_name }}.zip" dist/*.ttc
      - uses: softprops/action-gh-release@v2
        with:
          files: Lode-${{ github.ref_name }}.zip
          generate_release_notes: true
